export const eventPublished = [
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
    {
        Title: 'Healthy Heart Cardio Dance w/ Bonnie',
        Date: '2022-01-01',
        Category: 'Dance',
        EventDate: '2022-01-01',
        Type: 'In-person',
        Members: ["Bonnie", "John", "Doe"],
    },
]